export const PROFILE_TITLE = "Profile"
export const SIGN_OUT_TITLE = "Sign Out"
export const HOME_TITLE = "Home"
export const GALLERY_TITLE = "Gallery"
export const ALBUM_TITLE = "Album"
export const CAMERA_TITLE = "Camera"
export const SECTION_TITLE = "Sections"